<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search Review
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["Review/new", "Create Review"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "Review/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldContent" class="col-sm-2 control-label">Content</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["content", "size" => 30, "class" => "form-control", "id" => "fieldContent"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUserid" class="col-sm-2 control-label">UserId</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["userId", "type" => "number", "class" => "form-control", "id" => "fieldUserid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMovieid" class="col-sm-2 control-label">MovieId</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["movieId", "type" => "number", "class" => "form-control", "id" => "fieldMovieid"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
