<div class="page-header">
    <h1>Read/Comment/Rate your favourite Movies Reviews Here!!</h1>
</div>
<?php

echo "<h1>Welcome, please select an option:</h1>";

echo PHP_EOL;


if($this->session->has("userId")){
    echo $this->tag->linkTo(
    "movie/new",
    "<h2>Create a movie</h2>"
    );     
    echo $this->tag->linkTo(
    "movie/index",
    "<h2>Search movies</h2>"
    );     
        
     
    echo $this->tag->linkTo(
    "review/",
    "<h2>Search Reviews</h2>"
    );  
    
    echo $this->tag->linkTo(
    "logout",
    "<h2>Logout</h2>"
    );
}else{
       echo $this->tag->linkTo(
        "users/new",
        "<h2>Sign Up Here</h2>"
        );
        echo $this->tag->linkTo(
            "users/login",
            "<h2>Login Here</h2>"
        ); 
};





