<div class="page-header">
    <h1>Read/Comment/Rate your favourite Movies Reviews Here!</h1>
</div>
<?php

echo "<h2>Welcome, please select an option:</h2>";

echo PHP_EOL;


if($this->session->has("userId")){
    echo $this->tag->linkTo(
    "movie/new",
    "<div class='col-sm-8 text-left'> 
      <h3>Create a movie</h3>
    </div>"
    );     
    echo "</br>";  
    echo $this->tag->linkTo(
    "movie/index",
    "<div class='col-sm-8 text-left'> 
      <h3>Search Movies</h3>
    </div>"
    );     
        
     
    echo $this->tag->linkTo(
    "review/",
    "<div class='col-sm-8 text-left'> 
      <h3>Search Reviews</h3>
    </div>"
    );  
    
    echo $this->tag->linkTo(
    "logout",
    "<div class='col-sm-8 text-left'> 
      <h3>Logout</h3>
    </div>"
    );
}else{
       echo $this->tag->linkTo(
        "users/new",
        "<div class='col-sm-8 text-left'> 
        <h3>Sign up here</h3>
        </div>"
        );
        echo $this->tag->linkTo(
        "users/login",
        "<div class='col-sm-8 text-left'> 
        <h3>Login here</h3>
        </div>"
        ); 
};





