<div class="page-header">
    <h1>Read/Comment/Rate your favourite Movies Reviews Here!!</h1>
</div>
<?php

echo "<h1>Hello!</h1>";

echo PHP_EOL;


if($this->session->has("userId")){
    echo $this->tag->linkTo(
    "movie/new",
    "Create a movie!"
    );     
    echo "</br>";  
    echo $this->tag->linkTo(
    "movie/index",
    "Search movies!"
    );     
        
        echo "</br>";  
    echo $this->tag->linkTo(
    "review/",
    "Search Reviews!"
    );  
    
    echo "</br>";   
    echo $this->tag->linkTo(
    "logout",
    "Logout!"
    );
}else{
       echo $this->tag->linkTo(
        "users/new",
        "Sign Up Here!"
        );
        echo "</br>";   
        echo $this->tag->linkTo(
            "users/login",
            "Login Here!"
        ); 
};





