<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["movie/search", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit movie/Create Review
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "movie/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescription" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["description", "size" => 30, "class" => "form-control", "id" => "fieldDescription"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRating" class="col-sm-2 control-label">Rating</label>
    <div class="col-sm-10">
        <label>
           1 star(s)  <?php echo $this->tag->radioField(["rating", "type" => "radio", "value"=>1, "class" => "radio-inline", "id" => "fieldRating"]) ?>
        </label>
        <label>
           2 star(s)  <?php echo $this->tag->radioField(["rating", "type" => "radio", "value"=>2, "class" => "radio-inline", "id" => "fieldRating"]) ?>
        </label>
        <label>
           3 star(s)  <?php echo $this->tag->radioField(["rating", "type" => "radio", "value"=>3, "class" => "radio-inline", "id" => "fieldRating"]) ?>
        </label>
        <label>
           4 star(s)  <?php echo $this->tag->radioField(["rating", "type" => "radio", "value"=>4, "class" => "radio-inline", "id" => "fieldRating"]) ?>
        </label>
        <label>
           5 star(s)  <?php echo $this->tag->radioField(["rating", "type" => "radio", "value"=>5, "class" => "radio-inline", "id" => "fieldRating"]) ?>
        </label>
    </div>
</div>

<div class="form-group">
    <label for="fieldImageFile" class="col-sm-2 control-label">Upload your Image</label>
    <div class="col-sm-10">
        <?php echo $this->tag->fileField(["imageFile", "size" => 30, "class" => "form-control", "id" => "fieldImageFile"]) ?>
    </div>
</div>



<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["review/new", "Create Review"]) ?></li>
        </ul>
    </nav>
</div><?php


?>