<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["movie/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["movie/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Name</th>
            <th>Description</th>
            <th>Rating</th>
            <th>Image</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $movie): ?>
            <tr>
                <td><?php echo $movie->getId() ?></td>
            <td><?php echo $movie->getName() ?></td>
            <td><?php echo $movie->getDescription() ?></td>
            <td><?php echo $movie->getRating() ?></td>
            <td><img class="img-responsive center-block" 
		height="200" width="100" 
		src="data:image/jpeg;base64,<?php echo $movie->getImage() ?>"></td>

                <td><?php echo $this->tag->linkTo(["movie/edit/" . $movie->getId(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["movie/delete/" . $movie->getId(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("movie/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("movie/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("movie/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("movie/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
